### ISSUE TITLE
add manage of white-space: var(--tooltip-white-space);

### ISSUE THREAD

**Issue by guironne** [svelte-plugins/tooltips#10]
I would like to add -tooltip-white-space
:root {
    --tooltip-background-color: rgba(0, 0, 0, 0.9);
    --tooltip-border-radius: 4px;
    --tooltip-box-shadow: 0 1px 20px rgba(0, 0, 0, 0.25);
    --tooltip-font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen-Sans, Ubuntu, Cantarell,
      'Helvetica Neue', sans-serif;
    --tooltip-font-size: 14px;
    --tooltip-font-weight: 500;
    --tooltip-line-height: 1.25rem;
    --tooltip-color: #fff;
    --tooltip-offset-x: 0px;
    --tooltip-offset-y: 0px;
    --tooltip-padding: 12px;
    --tooltip-z-index: 100;
    --tooltip-arrow-size: 10px;
    --tooltip-white-space: pre-wrap;
  }

and 
.tooltip {
    background-color: var(--tooltip-background-color);
    box-shadow: var(--tooltip-box-shadow);
    border-radius: var(--tooltip-border-radius);
    color: var(--tooltip-color);
    opacity: 0;
    font-family: var(--tooltip-font-family);
    font-size: var(--tooltip-font-size);
    font-style: normal;
    font-weight: var(--tooltip-font-weight);
    line-height: var(--tooltip-line-height);
    padding: var(--tooltip-padding);
    position: absolute;
    text-align: left;
    visibility: hidden;
    white-space: var(--tooltip-white-space);
    z-index: var(--tooltip-z-index);
  }

  .tooltip.show {
    opacity: 1;
    visibility: visible;
    white-space: var(--tooltip-white-space);
  }

**Comment by dysfunc** [comment]
Added to the latest release https://github.com/svelte-plugins/tooltips/pull/15
