### ISSUE TITLE
manual open/close?

### ISSUE THREAD

**Issue by ogrotten** [svelte-plugins/tooltips#18]
I have a bit that was "click to open" > "click or mouseout to close" that I'm wanting to replace. 

Is there a flag to set or a method that can be fired to manually open/close the item?

I expect not, so therefore, how might the plugin might be modified to do so?

Thanks either way.

**Comment by dysfunc** [comment]
I'll add this feature request to the next release. 

**Feature Description**
Expose two new interface properties that define the `showAction` and `hideAction` of a tooltip. These properties will accept one of the following DOM event assignments: 
- **showAction**:  `click`, `mousedown`, `mouseenter`. 
- **hideAction**: `click`, `mouseout`, `mouseleave`.

**Comment by ogrotten** [comment]
That's pretty cool and useful. 

Might it be simpler to make methods to call using and svelte/html events? That way it can be dealt with directly.

like for example 

    <div on:mouseleave|stopPropagation={() => tooltip.close()} />

**Comment by dysfunc** [comment]
I had that thought initially. I could combine all of them so everything is out there. You can be explicit with events or control behavior via callbacks

**Comment by ogrotten** [comment]
That sounds great. Thanks and well done.

**Comment by dysfunc** [comment]
After thinking about it, I'm just going to make the `show` prop bindable and you can control the initial or close behavior by just setting that to `true` or `false`

**Comment by dysfunc** [comment]
you'll have something like this now

```svelte
<script>
  import { Tooltip } from '@svelte-plugins/tooltips';
  
  let isVisible = false;
  
  const hideOnClick = () => (isVisible = false);
</script>

<p>
 This tooltip should appear to the
  <Tooltip
    bind:show={isVisible}
    action="click"
    align="center"      
    content="I should appear to the right."
    position="right">
    <b>right</b>
  </Tooltip>
  when clicked.
</p>

<button on:click={hideOnClick}>Close the tooltip</button>
```

**Comment by ogrotten** [comment]
One of the things I dislike about github is that notifications are very out of the way. I'm always missing stuff. 

This looks fabulous thanks for your work!
