### ISSUE TITLE
Missing type definition for the tooltip action

### ISSUE THREAD

**Issue by jfosnight** [svelte-plugins/tooltips#19]
index.d.ts is missing the `export { tooltip } from "./action"`;

Suggested fix:
```typescript
export { default as Tooltip } from "./tooltip.svelte";
export { tooltip } from './action';
```

(Awesome library by the way, thanks!)

**Comment by dysfunc** [comment]
I'll be pushing a new update within the next 24 hours

**Comment by dysfunc** [comment]
Please a look at the PR and let me know if it looks good
