### ISSUE TITLE
Using additional on:mouseenter on element

### ISSUE THREAD

**Issue by adamnyberg** [svelte-plugins/tooltips#23]
Hi,

Very nice plugin! 🎉

I'm very new to frontend in general, I have an issue adding the tooltip to an element that already has a `on:mouseenter` when I add the tooltip as seen in my screenshots below. Any idea why this is happening? 🤔 

<img width="556" alt="image" src="https://github.com/svelte-plugins/tooltips/assets/1665236/1498d9e4-40e1-4732-8550-766f30f92234">

Without the tooltip it is working fine
<img width="540" alt="image" src="https://github.com/svelte-plugins/tooltips/assets/1665236/80ab70a9-4242-4d8f-bbf6-fcc709f87195">

**Comment by dysfunc** [comment]
Hey @adamnyberg! I tried to reproduce what you're seeing and I'm not able to. Take a look at this REPL https://svelte.dev/repl/b270777c27d74c6787776d8c65374b0b?version=4.2.7. Does `option.disabled_reason` have a valid or is it empty?
