### ISSUE TITLE
🐛 Tooltip has wrong position if it has a parent that's already positioned

### ISSUE THREAD

**Issue by DanielSidhion** [svelte-plugins/tooltips#25]
If there's an element in the page already positioned (e.g. already using `position: absolute` or some other form of non-standard positioning), the tooltip will show in the wrong place.

Reproduction: https://svelte.dev/repl/0468e8f7712f4b4fbf33a14ff1be2f0e?version=4.2.8

If the tooltip has any parent already positioned, it should figure out its positioning relative to that parent. Currently, the code assumes it'll always be the first positioned element in the tree.

**Comment by dysfunc** [comment]
Thanks for reporting this @DanielSidhion. The provided demo should be fixed now
