### ISSUE TITLE
🐛 Tooltip has wrong position if it has a parent with absolute position and moved transform

### ISSUE THREAD

**Issue by DanielSidhion** [svelte-plugins/tooltips#29]
If the tooltip is added to an element that has a parent with absolute position + moved transform, it gets positioned in the wrong place.

Reproduction: https://svelte.dev/repl/0468e8f7712f4b4fbf33a14ff1be2f0e?version=4.2.8

Reading the code (#27) that fixed the initial issue (#25), it looks like if an `offsetParent` has `absolute` positioning, it would be easier to just position the tooltip assuming the parent's bounding client rect is the (0, 0) origin, and ignore any previous `offsetParent`s that may exist in the tree. Basically, the code shouldn't expect `left` and `top` to determine the actual positioning of the element, but should still get the correct bounding rect using `.getBoundingClientRect()`.

More context: I'm using [Svelte Flow](https://svelteflow.dev/), and they define nodes with `position: absolute`, but move the nodes using `transform: translate(...)` instead of setting `left` and `top`.

**Comment by dysfunc** [comment]
#30 addresses this issue and fixes a bug introduced in the last change

**Comment by dysfunc** [comment]
Can you create a [REPL[(https://svelte.dev/repl/hello-world?version=4.2.8) with the issue?

**Comment by DanielSidhion** [comment]
@philmas My apologies, but I didn't understand well the scenario you mentioned. I tried creating a repro [here](https://svelte.dev/repl/e47685d17ecc47e8a3555531ab6887fc?version=4.2.8) with a few variations, and while I think those may have shown more bugs in the code, the behaviour was the same regardless of whether the page was scrolled or not.
