### ISSUE TITLE
🐛 Tooltip has wrong position with positioned parent(s)

### ISSUE THREAD

**Issue by DanielSidhion** [svelte-plugins/tooltips#37]
Follow up to #29. During discussion of that issue, I encountered a few more cases where the tooltip isn't positioned correctly when the tooltip has parents with `absolute` and/or `relative` positioning.

Reproduction: https://svelte.dev/repl/e47685d17ecc47e8a3555531ab6887fc?version=4.2.8

**Comment by dysfunc** [comment]
https://github.com/svelte-plugins/tooltips/pull/36 should address all of your issues. If you wouldnt mind, could you pull it down and let me know if this solves everything. I included all of your examples in the docs temporarily so you can just hover over the elements. @DanielSidhion

**Comment by DanielSidhion** [comment]
I just pulled v3.0.0 and can confirm the fix, and no regressions on my project so far. Thank you!
