### ISSUE TITLE
I don't think `hideOnOutsideClick` was merged in 3.0

### ISSUE THREAD

**Issue by Kai-Richardson** [svelte-plugins/tooltips#39]
**Describe the bug**
Despite the README and your PR referencing it, it doesn't appear to be anywhere in the code?

**Screenshots**
![image](https://github.com/svelte-plugins/tooltips/assets/49656058/f8ead073-d29d-4ab7-8616-773a7aa063f8)

**Comment by dysfunc** [comment]
It should be there https://github.com/svelte-plugins/tooltips/blob/main/src/tooltip.svelte#L39. Is this using an action?

**Comment by dysfunc** [comment]
Oh shoot. It's a typo in the docs. It should be `hideOnClickOutside`

**Comment by dysfunc** [comment]
I just updated the readme. Sorry about that
