### ISSUE TITLE
Add position position fixed mode

### ISSUE THREAD

**Issue by stalkerg** [svelte-plugins/tooltips#7]
Currently, the tooltip puts alongside the original element, and if, for example, the container has `overflow: hidden` it's broken. 
The tooltip shouldn't rely on the original element container.

**Comment by stalkerg** [comment]
or position absolute from root element how https://atomiks.github.io/tippyjs/ is work

**Comment by stalkerg** [comment]
also, very important to determine what input element should be immutable - https://github.com/svelte-plugins/tooltips/blob/main/src/action.js#L35 this is not working in many, many cases.

**Comment by dysfunc** [comment]
I planned to release a new tooltip version that provides absolute/fixed positioning. I just need to the time to work on it, which I currently don't. PR's are always welcome, though :)
